# -*- coding: utf-8 -*-
# @Author  : Ree

"""熔炼工具类，定义原版的熔炼配方"""

SMELTING_CONFIG_DICT = {
    # (原料, 产物, 产物方块True产物道具False)
    "minecraft:cactus": ("minecraft:dye", 2, False),
    "minecraft:clay": ("minecraft:hardened_clay", 0, True),
    "minecraft:coal_ore": ("minecraft:coal", 0, False),
    "minecraft:cobblestone": ("minecraft:stone", 0, True),
    "minecraft:diamond_ore": ("minecraft:diamond", 0, False),
    "minecraft:emerald_ore": ("minecraft:emerald", 0, False),
    "minecraft:gold_ore": ("minecraft:gold_ingot", 0, False),
    "minecraft:iron_ore": ("minecraft:iron_ingot", 0, False),
    "minecraft:kelp": ("minecraft:dried_kelp", 0, False),
    "minecraft:lapis_ore": ("minecraft:dye", 4, False),
    "minecraft:log": ("minecraft:coal", 1, False),
    "minecraft:log2": ("minecraft:coal", 1, False),
    "minecraft:netherrack": ("minecraft:netherbrick", 0, False),
    "minecraft:quartz_block": ("minecraft:quartz_block", 3, True),
    "minecraft:quartz_ore": ("minecraft:quartz", 0, False),
    "minecraft:red_sandstone": ("minecraft:red_sandstone", 3, True),
    "minecraft:redstone_ore": ("minecraft:redstone", 0, False),
    "minecraft:sand": ("minecraft:glass", 0, True),
    "minecraft:sandstone": ("minecraft:sandstone", 3, True),
    "minecraft:sea_pickle": ("minecraft:dye", 10, False),
    "minecraft:sponge:1": ("minecraft:sponge", 0, True),
    "minecraft:stained_hardened_clay:0": ("minecraft:white_glazed_terracotta", 0, True),
    "minecraft:stained_hardened_clay:1": (
        "minecraft:orange_glazed_terracotta",
        0,
        True,
    ),
    "minecraft:stained_hardened_clay:10": (
        "minecraft:purple_glazed_terracotta",
        0,
        True,
    ),
    "minecraft:stained_hardened_clay:11": ("minecraft:blue_glazed_terracotta", 0, True),
    "minecraft:stained_hardened_clay:12": (
        "minecraft:brown_glazed_terracotta",
        0,
        True,
    ),
    "minecraft:stained_hardened_clay:13": (
        "minecraft:green_glazed_terracotta",
        0,
        True,
    ),
    "minecraft:stained_hardened_clay:14": ("minecraft:red_glazed_terracotta", 0, True),
    "minecraft:stained_hardened_clay:15": (
        "minecraft:black_glazed_terracotta",
        0,
        True,
    ),
    "minecraft:stained_hardened_clay:2": (
        "minecraft:magenta_glazed_terracotta",
        0,
        True,
    ),
    "minecraft:stained_hardened_clay:3": (
        "minecraft:light_blue_glazed_terracotta",
        0,
        True,
    ),
    "minecraft:stained_hardened_clay:4": (
        "minecraft:yellow_glazed_terracotta",
        0,
        True,
    ),
    "minecraft:stained_hardened_clay:5": ("minecraft:lime_glazed_terracotta", 0, True),
    "minecraft:stained_hardened_clay:6": ("minecraft:pink_glazed_terracotta", 0, True),
    "minecraft:stained_hardened_clay:7": ("minecraft:gray_glazed_terracotta", 0, True),
    "minecraft:stained_hardened_clay:8": (
        "minecraft:silver_glazed_terracotta",
        0,
        True,
    ),
    "minecraft:stained_hardened_clay:9": ("minecraft:cyan_glazed_terracotta", 0, True),
    "minecraft:stone:0": ("minecraft:smooth_stone", 0, True),
    "minecraft:stonebrick:0": ("minecraft:stonebrick", 2, True),
    "minecraft:stripped_acacia_log": ("minecraft:coal", 1, False),
    "minecraft:stripped_birch_log": ("minecraft:coal", 1, False),
    "minecraft:stripped_dark_oak_log": ("minecraft:coal", 1, False),
    "minecraft:stripped_jungle_log": ("minecraft:coal", 1, False),
    "minecraft:stripped_oak_log": ("minecraft:coal", 1, False),
    "minecraft:stripped_spruce_log": ("minecraft:coal", 1, False),
    "minecraft:wood": ("minecraft:coal", 1, False),
    "minecraft:ice": ("minecraft:water", 0, True),
}
